name: Question
description: Ask a question about Speaky
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about Speaky? We're here to help!

        Before asking, please check:
        - [README documentation](https://github.com/guangzhaoli/Speaky#readme)
        - [Existing issues](https://github.com/guangzhaoli/Speaky/issues)

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      options:
        - Installation & Setup
        - Configuration
        - ASR (Speech Recognition)
        - LLM Post-processing
        - Usage & Features
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context that might help us answer your question.
      placeholder: Environment details, what you've already tried, etc.
